# GitHub Sponsors funding configuration for VimMaster

# GitHub Sponsors
github: A-Levin

# Buy Me a Coffee
custom: 
  - "https://buymeacoffee.com/alevin"
  - "https://ko-fi.com/alevin"
  - "https://opencollective.com/vim-master"
  - "https://qiwi.com/n/ALEVIN"

# Note: Telegram Stars и криптовалюты доступны в README.md